# escape=`
FROM microsoft/nanoserver:10.0.14393.1593

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" `
  org.label-schema.name="Gomematic UI" `
  org.label-schema.vendor="Thomas Boerger" `
  org.label-schema.schema-version="1.0"

EXPOSE 9000 80 443
VOLUME ["c:\\storage"]

ENV GOMEMATIC_UI_ASSETS c:\assets
ENV GOMEMATIC_UI_STORAGE c:\storage

ENTRYPOINT ["c:\\gomematic-ui.exe"]
CMD ["server"]

COPY dist/static c:\assets
COPY gomematic-ui.exe c:\gomematic-ui.exe
